### PR TITLE
percentage thresholds for memory, cpu and pods; additional performance outputs

### PR DESCRIPTION
**Pull request by steffeneichler**
- multi char options enabled (getopts replaced by getopt)
- define percentage thresholds for memory, cpu and pods (currently only supported in cluster specific node and cluster check type)
- functions added to convert units
- additional performance outputs for memory, cpu and pods

### CODE REVIEW

**Comment by Napsty** [comment]
Thanks for the contribution! :+1: 

As the PR is quite huge, it will take me some time to get through it, understand it and test it ;-)

**Review by Napsty — CHANGES_REQUESTED** [review]
In testing phase, looks good so far. But please keep the if condition style in place:

```if [[ condition ]]; then```

I know that every second developer would style it differently and its a personal opinion how to write if then, but keep the style as it was. 

Besides that, thanks for the contribution. Especially the added performance data on cluster level are very cool.

**Comment by steffeneichler** [comment]
Hi,

I changed the perf output again because there were problems with the interpretation of the unit "m" in influx.
The condition styles were also changed.

Kind regards
Steffen

**Review by Napsty — APPROVED** [review]

**Comment by Napsty** [comment]
Thank you @steffeneichler !

**Comment by Napsty** [comment]
Using on a couple of Rancher clusters now and verify for a few hours before releasing the new version.

**Pull request merged**
